# Generated by Django 3.2.6 on 2021-09-06 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Ism')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Familiya')),
                ('gender', models.CharField(choices=[('', ''), ('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, verbose_name='Jins*')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(90)], verbose_name='Yosh*')),
                ('place_of_birth', models.CharField(choices=[('', ''), ('Andijon', 'Andijon viloyati'), ('Buxoro', 'Buxoro viloyati'), ('Jizzax', 'Jizzax viloyati'), ('Qashqadaryo', 'Qashqadaryo viloyati'), ('Navoiy', 'Navoiy viloyati'), ('Namangan', 'Namangan viloyati'), ('Samarqand', 'Samarqand viloyati'), ('Surxondaryo', 'Surxondaryo viloyati'), ('Sirdaryo', 'Sirdaryo viloyati'), ('Toshkent', 'Toshkent viloyati'), ('Fargʻona', 'Fargʻona viloyati'), ('Xorazm', 'Xorazm viloyati'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston Respublikasi')], max_length=50, verbose_name="Tug'ilgan Joyi*")),
                ('place_of_residence', models.CharField(choices=[('', ''), ('Andijon', 'Andijon viloyati'), ('Buxoro', 'Buxoro viloyati'), ('Jizzax', 'Jizzax viloyati'), ('Qashqadaryo', 'Qashqadaryo viloyati'), ('Navoiy', 'Navoiy viloyati'), ('Namangan', 'Namangan viloyati'), ('Samarqand', 'Samarqand viloyati'), ('Surxondaryo', 'Surxondaryo viloyati'), ('Sirdaryo', 'Sirdaryo viloyati'), ('Toshkent', 'Toshkent viloyati'), ('Fargʻona', 'Fargʻona viloyati'), ('Xorazm', 'Xorazm viloyati'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston Respublikasi')], max_length=50, verbose_name='Yashash Joyi*')),
                ('favorite_team', models.CharField(choices=[('', ''), ('ARS', 'Arsenal'), ('CHE', 'Chelsea'), ('LIV', 'Liverpool'), ('MU', 'Manchester United'), ('MCI', 'Manchester City'), ('TOT', 'Tottenham'), ('BAY', 'Bayern Munich'), ('BVB', 'Borussia Dortmund'), ('ATM', 'Atletico Madrid'), ('BAR', 'Barcelona'), ('RM', 'Real Madrid'), ('JUV', 'Juventus'), ('INT', 'Inter'), ('ROMA', 'Roma'), ('NAP', 'Napoli'), ('ACM', 'Milan'), ('PSG', 'Paris Saint-Germain'), ('OL', 'Olympique Lyonnais'), ('LIL', 'Lille')], max_length=50, verbose_name='Jamoa*')),
            ],
        ),
    ]
